### ISSUE TITLE
lasted update is broken

### ISSUE THREAD

**Issue by ornithoptercat** [Craftjakob/Config-API#2]
Hello! The update of Config-API that you made today is causing the game to fail to open on mod loading.

**Comment by Craftjakob** [comment]
Ok, thanks for the report, but could you give me the modloader and the mod version and minecraft version, where it happens?

**Comment by Craftjakob** [comment]
Have found a crash bug in quilt, is it there?

**Comment by ornithoptercat** [comment]
it's the latest version for forge, Minecraft 1.20.4.

Dylan Maxwell
pronouns: they/them

**Comment by xLuPo** [comment]
New 1.20.1 Version works fine Clientside, crashes Serverside.
[crash-2024-03-15_09.30.46-fml.txt](https://github.com/Craftjakob/Config-API/files/14613565/crash-2024-03-15_09.30.46-fml.txt)

**Comment by Craftjakob** [comment]
Use the 2.1.0

Today, I will reset my computer and maybe also upload a fixed version.

**Comment by xLuPo** [comment]
Already downgraded.

**Comment by Craftjakob** [comment]
Okay fixed, I have to back port it and then you get the fixed version.

**Comment by Craftjakob** [comment]
I have fixed it, you can download the updated version in a few minutes.
